import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, String, Integer, DateTime, ForeignKey, Text
from sqlalchemy.orm import relationship
from app.core.database import Base

def generate_uuid() -> str:
    return str(uuid.uuid4())

class GeneratedArtifact(Base):
    """
    Stores structured artifacts generated by DeepTutor (e.g. Practice Questions, Quizzes, Flashcards)
    so they can be reliably referenced by the user in follow-up queries.
    """
    __tablename__ = "generated_artifacts"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    session_id = Column(String(36), ForeignKey("study_sessions.id", ondelete="CASCADE"), index=True, nullable=False)
    artifact_type = Column(String(50), index=True, nullable=False) # e.g., PRACTICE_QUESTION_SET, QUIZ
    title = Column(String(255), nullable=True) # e.g., "SVM Important Questions"
    status = Column(String(50), default="ACTIVE") # ACTIVE, ARCHIVED
    subject = Column(String(255), nullable=True)
    topic = Column(String(255), nullable=True)
    source_material_id = Column(String(36), nullable=True)
    
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    # Relationships
    session = relationship("StudySession", back_populates="generated_artifacts")
    items = relationship("GeneratedArtifactItem", back_populates="artifact", cascade="all, delete-orphan", order_by="GeneratedArtifactItem.item_index")

class GeneratedArtifactItem(Base):
    """
    Represents an individual item (e.g. Question 3) within a generated artifact.
    """
    __tablename__ = "generated_artifact_items"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    artifact_id = Column(String(36), ForeignKey("generated_artifacts.id", ondelete="CASCADE"), index=True, nullable=False)
    
    item_index = Column(Integer, nullable=False) # 1-based index (e.g. Question 1 -> 1)
    content = Column(Text, nullable=False)       # The exact question text
    topic = Column(String(255), nullable=True)   # The specific topic of this individual question
    
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    # Relationships
    artifact = relationship("GeneratedArtifact", back_populates="items")
