import { useState, useMemo } from 'react'
import DOMPurify from 'dompurify'
import { Copy, Check } from 'lucide-react'

interface Props {
  svg: string
}

/**
 * Renders an inline SVG diagram generated by the LLM.
 * Sanitizes the SVG with DOMPurify to strip scripts, event handlers,
 * and other XSS vectors before rendering via dangerouslySetInnerHTML.
 */
export default function InlineSVGDiagram({ svg }: Props) {
  const [copied, setCopied] = useState(false)

  const sanitizedSvg = useMemo(() => {
    if (!svg || !svg.trim()) return ''

    // Strip any surrounding markdown fences if present
    let raw = svg
      .replace(/^```svg\s*/i, '')
      .replace(/```$/, '')
      .trim()

    // DOMPurify with SVG-safe configuration
    const clean = DOMPurify.sanitize(raw, {
      USE_PROFILES: { svg: true, svgFilters: true },
      ADD_TAGS: [
        'svg', 'g', 'path', 'rect', 'circle', 'ellipse', 'line',
        'polyline', 'polygon', 'text', 'tspan', 'defs', 'marker',
        'linearGradient', 'radialGradient', 'stop', 'clipPath',
        'pattern', 'use', 'symbol', 'title', 'desc',
      ],
      ADD_ATTR: [
        'viewBox', 'xmlns', 'fill', 'stroke', 'stroke-width',
        'stroke-linecap', 'stroke-linejoin', 'stroke-dasharray',
        'cx', 'cy', 'r', 'rx', 'ry', 'x', 'y', 'x1', 'y1', 'x2', 'y2',
        'width', 'height', 'd', 'points', 'transform', 'opacity',
        'font-family', 'font-size', 'font-weight', 'text-anchor',
        'dominant-baseline', 'alignment-baseline',
        'marker-end', 'marker-start', 'marker-mid',
        'gradientUnits', 'gradientTransform', 'offset', 'stop-color', 'stop-opacity',
        'refX', 'refY', 'markerWidth', 'markerHeight', 'orient',
        'id', 'class', 'style', 'clip-path', 'href',
        'dx', 'dy', 'letter-spacing', 'writing-mode',
        'patternUnits', 'patternContentUnits',
      ],
      // Forbid dangerous elements and attributes
      FORBID_TAGS: ['script', 'foreignObject', 'iframe', 'object', 'embed'],
      FORBID_ATTR: ['onclick', 'onload', 'onerror', 'onmouseover', 'onfocus', 'onblur'],
    })

    if (!clean || !clean.includes('<svg')) return ''

    // Ensure responsive sizing: inject max-width style if not present
    const enhanced = clean.replace(/<svg\s+([^>]+)>/, (match, attrs) => {
      if (attrs.includes('style=')) {
        return match.replace(
          /style="([^"]*)"/,
          (_, existingStyle) =>
            `style="${existingStyle}; max-width: 100%; height: auto; display: block; margin: 0 auto;"`
        )
      }
      return `<svg ${attrs} style="max-width: 100%; height: auto; display: block; margin: 0 auto;">`
    })

    return enhanced
  }, [svg])

  const handleCopyCode = () => {
    const raw = svg.replace(/^```svg\s*/i, '').replace(/```$/, '').trim()
    navigator.clipboard.writeText(raw)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  if (!sanitizedSvg) {
    // Fallback: show raw SVG code if sanitization stripped everything
    return (
      <div className="my-4 p-4 rounded-xl bg-slate-50 border border-slate-200 text-xs font-mono text-slate-800 overflow-x-auto">
        <div className="text-slate-600 font-semibold mb-1 font-sans">Diagram Source</div>
        <pre>{svg}</pre>
      </div>
    )
  }

  return (
    <div className="my-4 w-full flex items-center justify-center overflow-x-auto relative group bg-transparent py-2">
      {/* Copy Button (matches MermaidDiagram style) */}
      <div className="absolute top-0 right-0 opacity-0 group-hover:opacity-100 transition-opacity z-10">
        <button
          onClick={handleCopyCode}
          title="Copy SVG Code"
          className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-white hover:bg-slate-50 border border-slate-200 text-xs font-medium text-slate-600 hover:text-slate-900 shadow-xs cursor-pointer transition"
        >
          {copied ? (
            <>
              <Check size={13} className="text-emerald-600" />
              <span className="text-emerald-700 text-xs font-medium">Copied</span>
            </>
          ) : (
            <>
              <Copy size={13} />
              <span className="text-xs">Copy</span>
            </>
          )}
        </button>
      </div>

      {/* Sanitized SVG rendered inline */}
      <div
        className="inline-svg-wrapper w-full flex items-center justify-center select-none overflow-x-auto"
        dangerouslySetInnerHTML={{ __html: sanitizedSvg }}
      />

      <style>{`
        .inline-svg-wrapper svg {
          overflow: visible !important;
          background: transparent !important;
          max-width: 100%;
          height: auto;
        }

        .inline-svg-wrapper text {
          font-family: 'Inter', 'Segoe UI', Arial, sans-serif !important;
        }
      `}</style>
    </div>
  )
}
