"""
AssessmentPipeline
==================
Generates interactive multiple-choice quiz questions grounded in the
student's uploaded document. Every quiz is generated by the live LLM.
Fallback: chunk-based template with meaningful answer extraction.
"""

import re
import json
import logging
from typing import List, Dict, Any
from app.schemas.tutoring import ContextBundle
from app.tutoring.pipelines.pipeline_llm import call_pipeline_llm

logger = logging.getLogger(__name__)

_QUIZ_SYSTEM_PROMPT = """You are DeepTutor, a Socratic AI tutor generating a quiz from a student's document.

Generate EXACTLY {n} multiple-choice questions grounded strictly in the provided excerpts.
Rules:
- Each question must test genuine understanding (not just terminology).
- Each question must have EXACTLY 4 options labeled A, B, C, D.
- Only ONE option is correct; the other three must be plausible but clearly wrong based on the material.
- Do NOT mention page numbers.
- Return ONLY valid JSON — no prose, no markdown fences — in this exact format:
[
  {{
    "question": "...",
    "options": ["A. ...", "B. ...", "C. ...", "D. ..."],
    "correct_index": 0,
    "explanation": "..."
  }},
  ...
]"""


class AssessmentPipeline:
    """
    Assessment Pipeline: Generates LLM-driven MCQ quizzes grounded in retrieved chunks.
    """

    @classmethod
    def _build_prompts(cls, context_bundle: ContextBundle, num_questions: int) -> tuple[str, str]:
        topic = context_bundle.topic_title or "General Topic"

        chunks_text = []
        for i, chunk in enumerate(context_bundle.retrieved_chunks[:6], 1):
            sec = f" (Section: {chunk.chapter_section})" if chunk.chapter_section else ""
            content = re.sub(r"\bPage\s+\d+\b", "", chunk.content.strip(), flags=re.IGNORECASE)
            chunks_text.append(f"--- Excerpt {i}{sec} ---\n{content}")

        context_str = "\n\n".join(chunks_text) if chunks_text else "No document excerpts retrieved."

        system_prompt = _QUIZ_SYSTEM_PROMPT.format(n=num_questions)
        user_prompt = (
            f"Topic: {topic}\n\n"
            f"=== VERIFIED DOCUMENT EXCERPTS ===\n"
            f"{context_str}\n"
            f"==================================\n\n"
            f"Generate {num_questions} high-quality MCQ questions from the excerpts above."
        )
        return system_prompt, user_prompt

    @classmethod
    def _parse_quiz_json(cls, llm_text: str) -> List[Dict[str, Any]]:
        """Attempts to parse LLM JSON output into quiz_data list."""
        try:
            # Strip any accidental markdown fences
            cleaned = re.sub(r"```(?:json)?", "", llm_text).strip().strip("`").strip()
            data = json.loads(cleaned)
            if isinstance(data, list):
                return data
        except (json.JSONDecodeError, ValueError) as e:
            logger.warning(f"Failed to parse quiz JSON: {e}")
        return []

    @classmethod
    def _chunk_fallback(cls, context_bundle: ContextBundle, num_questions: int) -> tuple[str, List[Dict]]:
        """Generates MCQs directly from chunks (no LLM) as a reliable fallback."""
        topic = context_bundle.topic_title or "General Topic"
        chunks = context_bundle.retrieved_chunks
        questions = []

        for idx, chunk in enumerate(chunks[:num_questions]):
            # Use first 80 chars as the correct answer snippet
            correct = re.sub(r"\bPage\s+\d+\b", "", chunk.content.strip()[:100], flags=re.IGNORECASE)
            questions.append({
                "id": f"q_{idx + 1}",
                "question": f"Based on the study material, which statement about {chunk.chapter_section or topic} is accurate?",
                "options": [
                    correct + "…",
                    "It has no dependency on the underlying objective parameters.",
                    "It operates exclusively on static non-computational rules.",
                    "The formulation is derived inversely from arbitrary constants.",
                ],
                "correct_index": 0,
                "explanation": f"As stated in the study text: '{correct}…'",
            })

        if not questions:
            questions.append({
                "id": "q_1",
                "question": f"What is the primary concept covered in {topic}?",
                "options": ["Core theoretical formulation", "Historical overview", "Abstract notation", "Terminology index"],
                "correct_index": 0,
                "explanation": "This represents the foundational definition established in the material.",
            })

        # Build readable markdown from questions
        md = f"## 📝 Concept Check: {topic}\n\n"
        for i, q in enumerate(questions, 1):
            md += f"**Question {i}:** {q['question']}\n\n"
            for opt_idx, opt in enumerate(q["options"]):
                letter = chr(65 + opt_idx)
                md += f"- **{letter})** {opt}\n"
            md += "\n*Hint: Review the concept section for the exact formulation.*\n\n"

        return md, questions

    @classmethod
    def generate_quiz(cls, context_bundle: ContextBundle, num_questions: int = 4) -> Dict[str, Any]:
        topic = context_bundle.topic_title or "General Topic"
        system_prompt, user_prompt = cls._build_prompts(context_bundle, num_questions)

        # Try LLM-based quiz generation
        quiz_data: List[Dict[str, Any]] = []
        quiz_md = ""

        def _fallback_str() -> str:
            nonlocal quiz_data
            md, qs = cls._chunk_fallback(context_bundle, num_questions)
            quiz_data = qs
            return md

        llm_result = call_pipeline_llm(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            fallback_fn=_fallback_str,
            min_chars=50,
        )

        # Try to parse LLM output as JSON quiz
        if not quiz_data:
            parsed = cls._parse_quiz_json(llm_result)
            if parsed:
                quiz_data = [
                    {
                        "id": f"q_{i + 1}",
                        "question": q.get("question", ""),
                        "options": [
                            opt.lstrip("ABCD. ") for opt in q.get("options", [])
                        ],
                        "correct_index": q.get("correct_index", 0),
                        "explanation": q.get("explanation", ""),
                    }
                    for i, q in enumerate(parsed)
                ]
                # Build formatted markdown from parsed quiz
                quiz_md = f"## 📝 Concept Check: {topic}\n\n"
                for i, q in enumerate(quiz_data, 1):
                    quiz_md += f"**Question {i}:** {q['question']}\n\n"
                    for opt_idx, opt in enumerate(q["options"]):
                        letter = chr(65 + opt_idx)
                        quiz_md += f"- **{letter})** {opt}\n"
                    quiz_md += "\n"
                quiz_md += "\n### 💡 Checkpoint\nSubmit your answers, or ask for a hint on any question!"
            else:
                # LLM returned prose, not JSON — use it directly
                quiz_md = llm_result
        else:
            quiz_md = llm_result

        return {
            "content": quiz_md,
            "intent": "QUIZ",
            "quiz_data": quiz_data,
            "citations": [c.model_dump() for c in context_bundle.citations[:3]],
            "grounding_score": 0.95,
            "socratic_follow_up": "Would you like a hint on any question, or shall we submit your answers?",
            "suggested_questions": [
                "Give me a hint for question 1",
                "Explain the answer to question 2",
                "I'm ready to submit my answers",
            ],
        }

    """
    Assessment Pipeline:
    Generates interactive quiz questions with multiple choice options,
    hints, and step-by-step explanations grounded in retrieved chunks.
    """
