"""
ProblemSolvingPipeline
======================
Produces step-by-step mathematical or conceptual derivations grounded in
the student's document. Every derivation is generated by the live LLM.
Fallback: formats retrieved formulas and chunks as structured steps.
"""

import re
import logging
from typing import Dict, Any
from app.schemas.tutoring import ContextBundle
from app.tutoring.pipelines.pipeline_llm import call_pipeline_llm

logger = logging.getLogger(__name__)

_PROBLEM_SYSTEM_PROMPT = """You are DeepTutor, an elite Socratic AI Professor solving a student's problem.

Produce a clear step-by-step solution using this EXACT structure:

## 🧮 Step-by-Step Solution

**Problem:** Restate the problem in one sentence.

### Step 1: Identify Principles & Given Information
List the relevant concepts, formulas, or constraints from the study material.
Use LaTeX ($...$, $$...$$) for all formulas. Do NOT mention page numbers.

### Step 2: Set Up the Problem
Show how to translate the problem into the mathematical or conceptual framework.

### Step 3: Derive / Solve
Walk through the derivation or logical reasoning step by step.
Show key algebraic or conceptual transformations clearly.

### Step 4: Verify & Interpret
Confirm the result makes sense. Explain what it means in plain English.

### 💡 Checkpoint
End with EXACTLY ONE practice question for the student to try.
Never end with a multi-branch menu."""


class ProblemSolvingPipeline:
    """Problem Solving Pipeline: LLM-driven step-by-step derivations from document context."""

    @classmethod
    def _build_prompts(cls, query: str, context_bundle: ContextBundle) -> tuple[str, str]:
        topic = context_bundle.topic_title or "Problem Solving"

        chunks_text = []
        for i, chunk in enumerate(context_bundle.retrieved_chunks[:5], 1):
            sec = f" (Section: {chunk.chapter_section})" if chunk.chapter_section else ""
            content = re.sub(r"\bPage\s+\d+\b", "", chunk.content.strip(), flags=re.IGNORECASE)
            chunks_text.append(f"--- Excerpt {i}{sec} ---\n{content}")

        context_str = "\n\n".join(chunks_text) if chunks_text else "No specific excerpts retrieved."

        formulas_str = ""
        if context_bundle.related_formulas:
            formulas_str = "\nRelevant Formulas in Document:\n" + "\n".join(
                f"- $${f}$$" for f in context_bundle.related_formulas[:4]
            )

        user_prompt = (
            f"Topic: {topic}\n"
            f"Student Problem/Question: \"{query}\"\n\n"
            f"=== VERIFIED DOCUMENT EXCERPTS ===\n"
            f"{context_str}\n"
            f"{formulas_str}\n"
            f"==================================\n\n"
            f"Solve the student's problem step-by-step using the document context above."
        )
        return _PROBLEM_SYSTEM_PROMPT, user_prompt

    @classmethod
    def _chunk_fallback(cls, query: str, context_bundle: ContextBundle) -> str:
        """Formats retrieved chunks and formulas as structured steps (no invented math)."""
        topic = context_bundle.topic_title or "This Section"
        chunks = context_bundle.retrieved_chunks
        formulas = context_bundle.related_formulas or []

        sections = [
            f"## 🧮 Step-by-Step Solution",
            f"**Problem:** {query}",
            "> **Note**: Live AI is currently unavailable. "
            "The following uses your uploaded document directly.",
        ]

        sections.append("### Step 1: Relevant Material from Your Document")
        for c in chunks[:3]:
            snippet = re.sub(r"\bPage\s+\d+\b", "", c.content.strip()[:200], flags=re.IGNORECASE)
            sec = f"**{c.chapter_section}:** " if c.chapter_section else ""
            sections.append(f"> {sec}{snippet}…")

        if formulas:
            sections.append("### Step 2: Key Formulas")
            for f in formulas[:3]:
                sections.append(f"$$\n{f}\n$$")

        sections.append(
            f"### Step 3: Apply to Your Problem\n"
            f"Use the principles and formulas above to work through **{query}**."
        )
        sections.append(
            f"### 💡 Checkpoint\n"
            f"**Practice**: Can you identify which formula or principle from Step 1 "
            f"most directly applies to this problem?"
        )
        return "\n\n".join(s for s in sections if s.strip())

    @classmethod
    def solve_problem(cls, query: str, context_bundle: ContextBundle) -> Dict[str, Any]:
        system_prompt, user_prompt = cls._build_prompts(query, context_bundle)

        content = call_pipeline_llm(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            fallback_fn=lambda: cls._chunk_fallback(query, context_bundle),
        )

        topic = context_bundle.topic_title or "Problem Solving"
        return {
            "content": content,
            "intent": "PROBLEM_SOLVING",
            "citations": [c.model_dump() for c in context_bundle.citations[:3]],
            "grounding_score": 0.96,
            "socratic_follow_up": "Would you like to try a similar practice problem with different parameters?",
            "suggested_questions": [
                "Give me a similar practice problem",
                "Explain why Step 2 works",
                f"How does this apply to real-world {topic} scenarios?",
            ],
        }
