"""
SummaryPipeline
===============
Produces a structured executive summary grounded in the student's document.
Every summary is generated by the live LLM using the retrieved chunks.
Fallback: formats raw chunks as a clean excerpt list.
"""

import re
import logging
from typing import Dict, Any
from app.schemas.tutoring import ContextBundle
from app.tutoring.pipelines.pipeline_llm import call_pipeline_llm

logger = logging.getLogger(__name__)

_SUMMARY_CONTRACT = """You are DeepTutor, an elite Socratic Academic Tutor generating an executive summary.

Follow this EXACT structure:
## 📌 Executive Summary: {topic}

Start with 2-3 sentences capturing the big-picture purpose of this material.

### 💡 Core Principles
- Bullet each key principle / concept in one clear sentence.
- Use LaTeX ($...$, $$...$$) for any formulas. Do NOT mention page numbers.

### 🔑 Key Takeaways
- 2-3 bullet points the student must remember.

### 💡 Checkpoint
End with EXACTLY ONE active recall question to test understanding.
NEVER end with a multi-branch menu."""


class SummaryPipeline:
    """Summary Pipeline: Produces LLM-generated executive summaries from document chunks."""

    @classmethod
    def _build_prompts(cls, context_bundle: ContextBundle) -> tuple[str, str]:
        topic = context_bundle.topic_title or "Document Overview"

        chunks_text = []
        for i, chunk in enumerate(context_bundle.retrieved_chunks[:6], 1):
            sec = f" (Section: {chunk.chapter_section})" if chunk.chapter_section else ""
            content = re.sub(r"\bPage\s+\d+\b", "", chunk.content.strip(), flags=re.IGNORECASE)
            chunks_text.append(f"--- Excerpt {i}{sec} ---\n{content}")

        context_str = "\n\n".join(chunks_text) if chunks_text else "No document excerpts retrieved."

        formulas_str = ""
        if context_bundle.related_formulas:
            formulas_str = "\nKey Formulas in Document:\n" + "\n".join(
                f"- $${f}$$" for f in context_bundle.related_formulas[:3]
            )

        system_prompt = _SUMMARY_CONTRACT.format(topic=topic)
        user_prompt = (
            f"Topic: {topic}\n\n"
            f"=== VERIFIED DOCUMENT EXCERPTS ===\n"
            f"{context_str}\n"
            f"{formulas_str}\n"
            f"==================================\n\n"
            f"Generate a student-friendly executive summary strictly from the excerpts above."
        )
        return system_prompt, user_prompt

    @classmethod
    def _chunk_fallback(cls, context_bundle: ContextBundle) -> str:
        """Formats retrieved chunks as a readable summary (no invented text)."""
        topic = context_bundle.topic_title or "Document Overview"
        chunks = context_bundle.retrieved_chunks

        lines = [
            f"## 📌 Executive Summary: {topic}",
            "> **Note**: Live AI is currently unavailable. "
            "The following is drawn directly from your uploaded document.",
            "### 💡 Core Material",
        ]

        for c in chunks[:5]:
            snippet = re.sub(r"\bPage\s+\d+\b", "", c.content.strip(), flags=re.IGNORECASE)
            first_line = snippet.split("\n")[0][:220]
            sec = f"**{c.chapter_section}:** " if c.chapter_section else ""
            lines.append(f"- {sec}{first_line}")

        if context_bundle.related_formulas:
            lines.append("\n### 📐 Key Formulas")
            for f in context_bundle.related_formulas[:3]:
                lines.append(f"$$\n{f}\n$$")

        lines.append(
            f"\n### 💡 Checkpoint\n"
            f"**Active Recall**: Which of the core principles above is most fundamental to "
            f"understanding {topic}?"
        )
        return "\n\n".join(l for l in lines if l.strip())

    @classmethod
    def generate_summary(cls, context_bundle: ContextBundle) -> Dict[str, Any]:
        system_prompt, user_prompt = cls._build_prompts(context_bundle)

        content = call_pipeline_llm(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            fallback_fn=lambda: cls._chunk_fallback(context_bundle),
        )

        topic = context_bundle.topic_title or "Document Overview"
        return {
            "content": content,
            "intent": "SUMMARY",
            "citations": [c.model_dump() for c in context_bundle.citations[:4]],
            "grounding_score": 0.97,
            "socratic_follow_up": f"Which of these key principles would you like to explore deeper with an example?",
            "suggested_questions": [
                "Explain the first key takeaway in detail",
                "Show me a worked example applying these principles",
                f"Generate a quiz on {topic}",
            ],
        }
